services:
  
  gateway:
    image: gateway
    build:
      context: ./Source/Services/ApiGateway
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - messages
      - identity
  
  messages:
    image: messages
    build:
      context: ./Source/Services/Messages
      dockerfile: WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Database: Host=postgres;Port=5432;Database=Messages;UserName=postgres;Password=postgres
    depends_on:
      - postgres

  identity:
    image: identity
    build:
      context: ./Source/Services/Identity
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Database: Host=postgres;Port=5432;Database=Identity;UserName=postgres;Password=postgres
      Jwt__Key: SuperSecretKeySuperSecretKeySuperSecretKeySuperSecretKeySuperSecretKeySuperSecretKey
    ports:
      - "23451:8080"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
